name: release project

on:
  issues:
    types:
      - closed

jobs:

  package:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout isx-cli
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          repository: "isxcode/isx-cli"
          ref: 'main'

      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup go env
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: './go.mod'

      - name: Install go modules
        run: |
          go env -w GO111MODULE=auto
          go mod tidy
          go install

      - name: isx_windows_amd64
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./target/isx_windows_amd64.exe main.go

      - name: isx_windows_arm64
        run: CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o ./target/isx_windows_arm64.exe main.go

      - name: isx_linux_amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./target/isx_linux_amd64 main.go

      - name: isx_darwin_arm64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ./target/isx_darwin_arm64 main.go

      - name: isx_darwin_amd64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./target/isx_darwin_amd64 main.go

      - name: Upload Package to Ali oss
        uses: chf007/aliyun-oss-upload-action@main
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.ALI_OSS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.ALI_OSS_KEY_SECRET }}
        with:
          region: oss-cn-shanghai
          bucket: isxcode
          source-dir: 'target'
          dest-dir: 'zhixingyun'