name: tag package

on:
  release:
    types: [published]

jobs:

  package:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout isx-cli
        uses: actions/checkout@v4

      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup go env
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: './go.mod'

      - name: Install go modules
        run: |
          go env -w GO111MODULE=auto
          go mod tidy
          go install

      - name: isx_windows_amd64
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./target/isx_windows_amd64.exe main.go

      - name: isx_linux_amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./target/isx_linux_amd64 main.go

      - name: isx_darwin_arm64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ./target/isx_darwin_arm64 main.go

      - name: isx_darwin_amd64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./target/isx_darwin_amd64 main.go

      - name: Upload BinaryFile
        uses: actions/upload-artifact@v3
        with:
          name: i-artifact
          path: |
            ./target/isx_windows_amd64.exe
            ./target/isx_linux_amd64
            ./target/isx_darwin_arm64
            ./target/isx_darwin_amd64

      - name: Publish to github
        uses: softprops/action-gh-release@v1
        with:
          files: target/*
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}